// End-to-end smoke test of the built site with a mock backend. Run: npm run build && npm test
import {chromium} from "playwright";import fs from "node:fs";import path from "node:path";import {fileURLToPath} from "node:url";import {serve} from "./serve.mjs";
const HERE=path.dirname(fileURLToPath(import.meta.url)),SHOTS=path.join(HERE,"test-results");fs.mkdirSync(SHOTS,{recursive:true});
const PORT=5177,BASE=`http://localhost:${PORT}`;const server=await serve(PORT);
const browser=await chromium.launch({...(process.env.KS_TEST_BROWSER?{channel:process.env.KS_TEST_BROWSER}:{}),args:["--use-gl=swiftshader","--enable-unsafe-swiftshader","--ignore-gpu-blocklist"]});
const mock=fs.readFileSync(path.join(HERE,"mock-backend.js"),"utf8");
const errors=[];let fails=0;const check=(ok,msg)=>{console.log((ok?"  ok   ":"  FAIL ")+msg);if(!ok)fails++;};
const ctx=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true,colorScheme:"light"});
await ctx.addInitScript(mock);
const page=await ctx.newPage();page.on("pageerror",e=>errors.push("app: "+e.message));page.on("console",m=>{if(m.type()==="error"){const loc=m.location();if(!loc.url.startsWith("https://fonts.googleapis.com/"))errors.push(`console: ${m.text()}${loc.url?` (${loc.url})`:""}`);}});

console.log("1. landing page");
await page.goto(BASE+"/");await page.waitForTimeout(600);
check(await page.title().then(t=>/Kitchen Studio/.test(t)),"title");
check(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),"no horizontal scroll on phone");
check(await page.locator(".brand svg").count()===1&&/Vibe your kitchen/.test(await page.textContent(".brand")),"approved logo and tagline on landing page");
await page.setViewportSize({width:320,height:844});
check(await page.evaluate(()=>{const a=document.querySelector("header .brand").getBoundingClientRect(),buttons=[...document.querySelectorAll("header .btn")].map(b=>b.getBoundingClientRect());return buttons.every(b=>a.right+8<=b.left&&b.right<=innerWidth)&&document.documentElement.scrollWidth<=innerWidth;}),"logo and navigation fit a 320px phone");
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:path.join(SHOTS,"brand-landing-phone.png")});
check(!(await page.locator("#wlForm").isHidden()),"waitlist form shown with backend");
check(await page.locator("#wlConsent").getAttribute("required")!==null,"waitlist requires explicit marketing consent");
await page.fill("#wlEmail","chef@example.com");await page.check("#wlConsent");await page.click("#wlBtn");await page.waitForTimeout(300);
check(/on the list/.test(await page.textContent("#wlMsg")),"waitlist submit");

console.log("2. app, signed out");
await page.goto(BASE+"/app/");await page.waitForTimeout(1200);
check(!(await page.locator("#kitchensBtn").isHidden()),"kitchens button visible");
check(/sign in/.test(await page.textContent("#saveState")),"save label asks to sign in: "+await page.textContent("#saveState"));
await page.click("#kitchensBtn");await page.waitForTimeout(300);
check(await page.locator("#dlg").evaluate(d=>d.open),"sign-in dialog opens");
check(/Sign in/.test(await page.textContent("#dlgTitle")),"dialog is sign-in");
await page.fill("#siEmail","chef@example.com");await page.click("#siSend");await page.waitForTimeout(900);
check(!(await page.locator("#dlg").evaluate(d=>d.open)),"dialog closed after sign-in");
check(/Saved online/.test(await page.textContent("#saveState")),"first kitchen created online: "+await page.textContent("#saveState"));
const list1=await page.evaluate(()=>JSON.parse(localStorage.getItem("ks.mock")).projects);check(list1.length===1,"one project in backend");
const conflict=await page.evaluate(async()=>{const s=JSON.parse(localStorage.getItem("ks.mock")),p=s.projects[0],v=p.version;p.version=v+1;localStorage.setItem("ks.mock",JSON.stringify(s));let code="";try{await window.KS_backend.saveProject(p.id,p.data,p.name,v);}catch(e){code=e.code||"";}p.version=v;localStorage.setItem("ks.mock",JSON.stringify(s));return code;});
check(conflict==="conflict","stale cloud save is rejected");

console.log("3. edit, my kitchens, rename, new kitchen");
await page.click("#t-room");await page.fill("#roomW","7000");await page.dispatchEvent("#roomW","change");await page.reload();await page.waitForTimeout(1600);
check((await page.inputValue("#roomW"))==="7000","last edit survives an immediate page reload");
const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem("ks.mock")).projects[0].data.room.w);check(saved===7000,"edit persisted to backend (room w=7000)");
await page.click("#kitchensBtn");await page.waitForTimeout(400);
check(/My kitchens/.test(await page.textContent("#dlgTitle")),"my kitchens dialog");
check((await page.locator(".krow").count())===1,"one row listed");
await page.click('.krow [data-act="rename"]');await page.waitForTimeout(200);await page.fill("#askIn","Burger cloud kitchen");await page.click("#askOk");await page.waitForTimeout(500);
check(/Burger cloud kitchen/.test(await page.textContent(".klist")),"renamed in list");
await page.screenshot({path:path.join(SHOTS,"test-kitchens.png")});
await page.click("#kNew");await page.waitForTimeout(200);await page.fill("#askIn","Café Riyadh");await page.click("#askOk");await page.waitForTimeout(700);
const list2=await page.evaluate(()=>JSON.parse(localStorage.getItem("ks.mock")).projects);check(list2.length===2,"second project created");
check(/Café Riyadh/.test(await page.textContent("#saveState")),"header shows new kitchen name");
check((await page.evaluate(()=>document.querySelectorAll(".it").length))===0,"new kitchen is empty");

console.log("4. share link");
await page.click("#menuBtn");await page.click("#mShare");await page.waitForTimeout(400);
const url=await page.inputValue("#shUrl");check(/\/k\/[A-Za-z0-9]{8,}/.test(url),"share url: "+url);
await page.click("#dlgClose");
// open in a fresh context (another person, signed out)
const ctx2=await browser.newContext({viewport:{width:1280,height:900}});await ctx2.addInitScript(mock);
const p2=await ctx2.newPage();p2.on("pageerror",e=>errors.push("shared: "+e.message));
// share state lives in the first context's localStorage; copy it across
const st=await page.evaluate(()=>localStorage.getItem("ks.mock"));await p2.addInitScript(s=>{const j=JSON.parse(s);j.user=null;localStorage.setItem("ks.mock",JSON.stringify(j));},st);
await p2.goto(url);await p2.waitForTimeout(1200);
check(!(await p2.locator("#banner").isHidden()),"shared banner shown");
check(/Café Riyadh/.test(await p2.textContent("#banner")),"banner names the kitchen");
check(p2.url().endsWith("/app/"),"url rewritten to /app/ after loading the share");
await p2.click("#bnSave");await p2.waitForTimeout(300);check(/Sign in/.test(await p2.textContent("#dlgTitle")),"save-copy asks to sign in when signed out");
await ctx2.close();

console.log("5. sign out keeps local copy");
await page.click("#menuBtn");await page.click("#mSignOut");await page.waitForTimeout(500);
check(/sign in to save online/.test(await page.textContent("#saveState")),"signed-out label");
check(/Café Riyadh/.test(await page.textContent("#saveState")),"kitchen name kept locally");

console.log("5b. report a gap (signed out, with layout attached)");
if(await page.locator("#menu").isHidden())await page.click("#menuBtn");await page.click("#mReport");await page.waitForTimeout(200);
check(/Report a gap/.test(await page.textContent("#dlgTitle")),"report dialog opens");
await page.click("#rpSend");check(/few words/.test(await page.textContent("#rpNote")),"empty report is refused");
await page.selectOption("#rpKind","drawing");await page.fill("#rpMsg","Lowboy draws doors, it has drawers");await page.fill("#rpEmail","chef@example.com");
await page.click("#rpSend");await page.waitForTimeout(400);
const reps=await page.evaluate(()=>JSON.parse(localStorage.getItem("ks.mock")).reports||[]);
check(reps.length===1&&reps[0].kind==="drawing"&&reps[0].email==="chef@example.com","report stored with kind and email");
check(reps[0]&&reps[0].project&&Array.isArray(reps[0].project.items)&&reps[0].context&&reps[0].context.view,"report carries the layout and context");
check(/Thanks/.test(await page.textContent("#dlgBody")),"report thank-you shown");await page.click("#rpDone");

console.log("6. screenshots for the landing page (desktop plan, phone plan, 3D)");
const d=await browser.newContext({viewport:{width:1280,height:900},deviceScaleFactor:1,colorScheme:"light"});await d.addInitScript(mock);const dp=await d.newPage();dp.on("pageerror",e=>errors.push("desk: "+e.message));
await dp.goto(BASE+"/app/");await dp.waitForTimeout(1500);await dp.click("#t-eq");await dp.waitForTimeout(400);await dp.screenshot({path:path.join(SHOTS,"plan-desktop.png")});
await dp.click("#v3dBtn");await dp.waitForTimeout(2500);await dp.screenshot({path:path.join(SHOTS,"3d.png"),clip:{x:400,y:0,width:800,height:900}});
console.log("7. branded drawing exports, A3 and A4");
await dp.click("#vPlan");
await dp.click("#t-sch");
await dp.addScriptTag({url:BASE+"/app/vendor/jspdf.min.js"});
await dp.addScriptTag({url:BASE+"/app/vendor/svg2pdf.min.js"});
await dp.evaluate(()=>{
  window.__drawingSheets=[];
  const original=window.jspdf.jsPDF.API.svg;
  window.jspdf.jsPDF.API.svg=function(svg,options){
    const logo=svg.querySelector('[data-ks-brand="lockup"]'),box=logo?.getBBox();
    window.__drawingSheets.push({svg:svg.outerHTML,logo:!!logo,tagline:logo?.textContent.includes("Vibe your kitchen"),fits:!!box&&box.x>=-1&&box.x+box.width<=501&&box.y>=-1&&box.y+box.height<=101});
    return original.call(this,svg,options);
  };
});
for(const paper of ["a3","a4"]){
  await dp.selectOption("#pdfPaper",paper);
  await dp.locator("#pdf3d").setChecked(paper==="a3");
  await dp.evaluate(()=>window.__drawingSheets=[]);
  const pending=dp.waitForEvent("download",{timeout:60000});
  await dp.click("#expPdf");
  const pdf=await pending,file=path.join(SHOTS,"branded-"+paper+".pdf");
  await pdf.saveAs(file);
  check(fs.readFileSync(file).subarray(0,5).toString()==="%PDF-","valid "+paper.toUpperCase()+" PDF downloaded");
  const sheets=await dp.evaluate(()=>window.__drawingSheets);
  check(sheets.length>=4&&sheets.every(s=>s.logo&&s.tagline&&s.fits),"logo is visible and fits on every "+paper.toUpperCase()+" drawing sheet ("+sheets.length+" sheets)");
  check(sheets.some(s=>s.svg.includes("Stainless fabrication details")&&/F1 /.test(s.svg)&&s.svg.includes("FRONT")&&s.svg.includes("SIDE")),"fabrication detail sheet with plan, front and side views on "+paper.toUpperCase());
  fs.writeFileSync(path.join(SHOTS,"branded-"+paper+"-first.svg"),sheets[0].svg);
  fs.writeFileSync(path.join(SHOTS,"branded-"+paper+"-last.svg"),sheets.at(-1).svg);
}
console.log("8. fabrication details on stainless items");
await dp.click("#t-eq");
const fabId=await dp.evaluate(()=>{const it=KS_ui.items().find(i=>i.kind==="ss"&&/^sink|table/.test(i.ssType));KS_ui.select(it.id);return it.id;});
await dp.waitForTimeout(200);
check(await dp.locator("#fabD").count()===1,"stainless item shows fabrication details");
await dp.evaluate(()=>{document.getElementById("fabD").open=true;});
await dp.selectOption("#fab_upstand","150 mm");await dp.waitForTimeout(200);
check(await dp.evaluate(id=>KS_ui.items().find(i=>i.id===id).fab?.upstand==="150 mm",fabId),"changing a fabrication detail is saved on the item");
check(await dp.locator("#fabD[open]").count()===1,"details stay open after an edit");
await dp.evaluate(()=>KS_ui.deselect());await dp.click("#t-sch");
const svgPending=dp.waitForEvent("download");
await dp.click("#expSvg");const svgDownload=await svgPending,svgFile=path.join(SHOTS,"branded-plan.svg");await svgDownload.saveAs(svgFile);
const svg=fs.readFileSync(svgFile,"utf8");
check(svg.includes('data-ks-brand="lockup"')&&svg.includes("Vibe your kitchen"),"standalone plan SVG includes the logo and tagline");
const layout=await dp.evaluate(svg=>{const doc=new DOMParser().parseFromString(svg,"image/svg+xml"),v=doc.documentElement.getAttribute("viewBox").split(" ").map(Number),paper=doc.querySelector("rect"),p=["x","y","width","height"].map(k=>+paper.getAttribute(k));return v[0]===p[0]&&v[1]===p[1]&&v[2]===p[2]&&v[3]>p[3];},svg);
check(layout,"SVG branding adds space below the plan without cropping or rescaling the drawing");
await dp.screenshot({path:path.join(SHOTS,"brand-app-desktop.png")});
await dp.evaluate(()=>KS_ui.setTheme("dark"));await dp.screenshot({path:path.join(SHOTS,"brand-app-dark.png")});
await dp.evaluate(()=>KS_ui.setTheme("light"));

console.log("9. undo, redo and a person in the aisle");
const n0=await dp.evaluate(()=>KS_ui.items().length);
await dp.click("#personBtn");await dp.waitForTimeout(300);
const person=await dp.evaluate(()=>KS_ui.items().find(i=>i.archType==="person"));
check(!!person&&person.w===600,"Person button drops a 600 mm figure into the plan");
check(await dp.evaluate(()=>KS_ui.items().length)===n0+1,"one item added");
check(/\d{3,4}/.test(await dp.textContent("#aisleG")),"aisle widths are drawn around the person: "+(await dp.textContent("#aisleG")));
check(/clear/.test(await dp.textContent("#selbar")),"selection panel reads the clear aisle width");
await dp.screenshot({path:path.join(SHOTS,"person-aisle.png")});
check(!(await dp.locator("#undoBtn").isDisabled()),"undo is enabled after a change");
await dp.click("#undoBtn");await dp.waitForTimeout(300);
check(await dp.evaluate(()=>KS_ui.items().length)===n0&&!(await dp.evaluate(()=>KS_ui.items().some(i=>i.archType==="person"))),"undo removes the person");
await dp.click("#redoBtn");await dp.waitForTimeout(300);
check(await dp.evaluate(()=>KS_ui.items().some(i=>i.archType==="person")),"redo brings the person back");
await dp.click("#svg",{position:{x:5,y:5}}).catch(()=>{});await dp.keyboard.press("Control+z");await dp.waitForTimeout(300);
check(await dp.evaluate(()=>KS_ui.items().length)===n0,"Ctrl+Z undoes too");
await d.close();
const ph=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true,colorScheme:"light"});await ph.addInitScript(mock);const pp=await ph.newPage();
await pp.goto(BASE+"/app/");await pp.waitForTimeout(1500);await pp.click("#zIn");await pp.waitForTimeout(400);await pp.screenshot({path:path.join(SHOTS,"plan-phone.png")});await ph.close();
check(errors.length===0,"no page errors"+(errors.length?": "+errors.join(" | "):""));
await browser.close();server.close();
console.log(fails?`\n${fails} check(s) failed`:"\nall checks passed");process.exit(fails?1:0);
